server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guava
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: false
    database: mysql
