spring:
  server:
    port: 8085

  cors:
    allowed-origins: "*"

#  jdbc:mysql://localhost:3306/guava?useSSL=false&serverTimeZone=UTC*useLegacyDateTimeCode=false
  datasource:
    url: jdbc:mysql://containers-us-west-45.railway.app:5633/railway?useSSL=false&serverTimeZone=UTC*useLegacyDateTimeCode=false
    username: root
    password: xeIvYqJbYrwVXbzGXEaU
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
#    database-platform: org.hibernate.dialect.MySQLInnoDBDialect

  debug: true

  spring.mvc.pathmatch.matching-strategy: ant_path_matcher

  STRIPE_SECRET_KEY: sk_test_51MevffJ7qeZtbDAlnjOB9rNdQVtptp7nelM4vP8JVXDJUafp2LVEdpOv1PQ7HDTyo8zQt9laJeN56Sbco0SQjDRy00Tk5xLMiu

#  BASEURL: http://localhost:8082/

